# Generated by Django 5.1.3 on 2024-11-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demogallery',
            name='img_Info',
            field=models.TextField(default='', max_length=500),
        ),
    ]
