# Generated by Django 4.2.16 on 2024-11-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsmusers', '0003_alter_employeeprofile_age'),
        ('tsmtasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tsmusers.employee'),
        ),
    ]
