# Generated by Django 4.2.16 on 2024-11-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmusers', '0002_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
