# Generated by Django 4.2.16 on 2024-11-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tsmusers', '0003_alter_employeeprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='Task Name')),
                ('task_description', models.TextField(verbose_name='Task Description')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, verbose_name='Priority')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Failed', 'Failed')], default='In Progress', max_length=20)),
                ('assigned_employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tsmusers.employeeprofile')),
            ],
        ),
    ]
